[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_and_transfer_token = "6azXDMKVeDTXeHCueTfba2F7YCkHfU1tQ6ZoA4MVb4WG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rishabhvasudevan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
